Composer libraries requirements update for PHP >=8.0 support. resolves #18
DoclerLabs/codeception-slim-module pull request #19
Opened 2022-03-01 12:05 UTC by xklid101

Dropped PHP 7 support.

2022-03-04 20:53 UTC, szhajdu commented on composer.json
>          "slim/psr7": "^1.1",
Please also set to ^1.3. PHP 8 support came with that version.

2022-03-04 20:53 UTC, szhajdu commented on composer.json
>          "slim/slim": "^4.2"
Please set to ^4.7 as well.

2022-03-04 20:54 UTC, szhajdu requested changes
Thank you for your contribution, please check my comments.

2022-03-05 17:30 UTC, xklid101 commented
Made requested chages (in 5a2e0ea91faf76cd42c169f34e37f9e507f27de0), should be ok now. You can check it out. Thanks.

2022-03-07 09:21 UTC, xklid101 commented
Just info, that new commit 8d2d586d5deda543ddf2c9ca5e104abfa3e905c0 has fixed github static analysis actions and its php8 requirement

2022-03-08 06:17 UTC, merged